### ISSUE TITLE
Feature Request: Can we have the error message have more information?

### ISSUE THREAD

**Issue by aconstanti** [pwall567/json-kotlin#1]
eg: When an object fails to deserialise because no suitable constructor can be found, can we:

a) print the properties of the json object?
b) I am open to suggestions 🤷‍♂️

**Comment by pwall567** [comment]
This is a reasonable request, but the solution may not be straightforward.  I'd like to think there could be a more helpful message than just a list of properties - it may not be obvious why those properties didn't satisfy any of the constructors.

Leave it with me; I'll look into this with some urgency.

**Comment by pwall567** [comment]
OK, version 4.0 of `json-kotlin` includes two major changes to the content of exception messages:
1. Many messages now include a JSON Pointer indicating the location in the JSON where the error occurred
2. Exceptions caused by the inability to locate a constructor matching the available JSON properties will now include either a) a list of the missing properties if the class has only one constructor, or b) a list of the properties present if the class has multiple constructors.

This is being treated as a breaking change, requiring an increment of the major version number, because there may be code that is dependent on the exact content of the exception messages.

**Comment by aconstanti** [comment]
Looks good. Thank you.
